### PR TITLE
Added peek and pop support for the comics.

### PR DESCRIPTION
**Pull request by avikantz**
Addresses issue #55

### CODE REVIEW

**Comment by mamaral** [comment]
Hey sorry I didn't see this earlier. I was a good ways through converting the structure of the comic list to use the MVP design pattern, but hadn't yet committed my changes. If you wanted to rebase these changes against the current master branch I'd love this functionality. Do you have a screenshot of how it looks?

**Comment by avikantz** [comment]
It's alright, there are too many changes made since the PR to be rebased successfully. It was implemented according to the old convention, not MVC.

Here's how it looks though.
Screen

**Comment by mamaral** [comment]
The conflict was actually a minor one, I believe I fixed all the issues and would love to get this into the app. What do you think?

**Comment by avikantz** [comment]
Alright, sounds cool.

**Pull request merged**
