### PR TITLE
Add random comic button to comic view

### PR DESCRIPTION
**Pull request by NguyenDytrich**
Before
=====
<a href="http://imgur.com/5zf75XK"></a>

After
====
<a href="http://imgur.com/unJ9FUN"></a>

### CODE REVIEW

**Comment by mamaral** [comment]
Awesome - looks good. Going to look at why travis failed. Thanks!

**Comment by NguyenDytrich** [comment]
Updated the travis.yml to use the xcode7.2 osx image, build should be green now.

**Comment by NguyenDytrich** [comment]
Updated the travis.yml to use xcode 7.2. Tests failed due to timeout. Everything should be good to go.

**Comment by mamaral** [comment]
Perfect, thanks again!

**Pull request merged**
