### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by RyanCopley**

### CODE REVIEW

**Comment by RyanCopley** [comment]
@mamaral - There is still a bug in the uploader, I asked Steve to merge the fix but he hasn't yet to my knowledge. When it does, it will auto apply to your repo.

**Comment by mamaral** [comment]
Cool, thanks again. Will I still need the codecov file in my repo?

**Comment by RyanCopley** [comment]
Nope

**Comment by RyanCopley** [comment]
It should be good to fo

**Comment by RyanCopley** [comment]
Go*

**Comment by mamaral** [comment]
Excellent, thanks!

**Pull request merged**
